version: "3.3"

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1433:1433 # Default MSSQL Port
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: testPassword@
  redis:
    image: redis:7
    ports:
      - 6379:6379
  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testPassword
    ports:
      - "27017:27017"
